### PR TITLE
Prevent `SubmitGradeForm` styling from applying to error dialogs

### LINKED ISSUE #3352: Error dialog is broken when LTI Outcomes (grading) requests fail
Screenshot from 2021-11-08 14-00-37

Here's how it looks after expanding the **Error Details**:

Screenshot from 2021-11-08 14-19-42

To reproduce it hack the code like so:

```diff
diff --git a/lms/services/lti_outcomes.py b/lms/services/lti_outcomes.py
index 51e1bda0..18bfcd3e 100644
--- a/lms/services/lti_outcomes.py
+++ b/lms/services/lti_outcomes.py
@@ -127,7 +127,7 @@ class LTIOutcomesClient:
         """Return the POX body element, checking for errors."""
 
         try:
-            body = data["imsx_POXEnvelopeResponse"]["imsx_POXBody"]
+            body = data["imsx_POXEnvelopeResponse"]["foo"]
             header = data["imsx_POXEnvelopeResponse"]["imsx_POXHeader"]
             status = header["imsx_POXResponseHeaderInfo"]["imsx_statusInfo"][
                 "imsx_codeMajor"
```

Then launch any Moodle assignment as a teacher and select a student from the grading bar. (You may have to launch the assignment as a student first, in order to get a student to appear in the grading bar.)

Here's the body of the backend's 400 error response to the `/api/lti/result` response looks like:

```json
{"message": "Malformed LTI outcome response", "details": {"request": {"method": null, "url": null}, "response": {"status_code": 200, "reason": "OK"}, "validation_errors": null}}
```

### PR DESCRIPTION
**Pull request by lyzadanger**
Render `ErrorDialog`s (when relevant) outside of the component's
`<form>` element to prevent form styling, etc., from interfering with
the dialog contents.

The cause of #3352 specifically was a `white-space: nowrap` rule applied to `.SubmitGradingForm`. This was being applied to dialog contents (because the dialog was inside of `form.SubmitGradingForm`), causing the dialog to have horizontal scroll.

## Before

This is on Chrome. In some browsers/OSes, this will look different, e.g. may have a scrollbar always visible:

The description is cut off on the right mid-sentence:

Screen Shot 2021-11-08 at 11 36 44 AM

Scrolling right looks like:

Screen Shot 2021-11-08 at 11 36 53 AM

## After

Everything fits as expected:

Screen Shot 2021-11-08 at 11 36 22 AM

Fixes #3352

## Testing

There are steps to reproduces this error in the original issue #3352

### CODE REVIEW

File: lms/static/scripts/frontend_apps/components/SubmitGradeForm.js [hunk 1]
```diff
@@ -161,50 +161,58 @@ export default function SubmitGradeForm({ student }) {
...
-        type="submit"
-        className="SubmitGradeForm__submit"
-        disabled={disabled}
-        onClick={onSubmitGrade}
-      >
-        <Icon classes="SubmitGradeForm__check-icon" name="check" /> Submit Grade
-      </button>
+          onClick={onSubmitGrade}
+        >
+          <Icon classes="SubmitGradeForm__check-icon" name="check" /> Submit
```
Comment (robertknight) [inline lms/static/scripts/frontend_apps/components/SubmitGradeForm.js:207]: This text wrapping is a bit awkward. Can we fix that without having Prettier revert it?

File: lms/static/scripts/frontend_apps/components/SubmitGradeForm.js [hunk 2]
```diff
@@ -161,50 +161,58 @@ export default function SubmitGradeForm({ student }) {
...
+          Grade
+        </button>
+        {gradeSaving && (
+          <div className="SubmitGradeForm__loading-backdrop">
+            <Spinner className="SubmitGradeForm__submit-spinner" />
+          </div>
+        )}
+      </form>
       {!!submitGradeError && (
```
Comment (robertknight) [inline lms/static/scripts/frontend_apps/components/SubmitGradeForm.js:216]: Note a change in this code, but the use of `!!` here is unnecessary AFAIK, since the `&&` operator automatically coerces its argument to a boolean. Same with the `fetchGradeError` test below.

**Review by robertknight — APPROVED** [review]
LGTM. An alternative would be to apply some reset to a parent of dialog or to apply the `white-space: nowrap` rule more narrowly. The approach in this PR looks sensible though.

File: lms/static/scripts/frontend_apps/components/SubmitGradeForm.js (hunk 1 above)
Comment (lyzadanger) [reply lms/static/scripts/frontend_apps/components/SubmitGradeForm.js:207]: Nope. Prettier seems pretty determined here. When next touching this component, I'd like to convert this over to a "real" Button component anyway.
