### PR TITLE
Dialog visual fixes

### LINKED ISSUE #2320: Error dialog when fetching a grade fails is different from other error dialogs
## Problem

The error dialog that's shown when fetching a grade fails is different from other dialogs in the app:

Screenshot from 2020-12-21 11-15-07

Screenshot from 2020-12-21 11-14-51

## Reproducing

Apply the diff below to cause fetching grades to fail. Then log in to hypothesisuniversity.moodlecloud.com as a teacher, launch an assignment, and go to a student.

```diff
diff --git a/lms/services/lti_outcomes.py b/lms/services/lti_outcomes.py
index 5bf7cd77..bccd62d6 100644
--- a/lms/services/lti_outcomes.py
+++ b/lms/services/lti_outcomes.py
@@ -134,6 +134,7 @@ class LTIOutcomesClient:
             status = header["imsx_POXResponseHeaderInfo"]["imsx_statusInfo"][
                 "imsx_codeMajor"
             ]
+            foo = data["foo"]
 
         except KeyError as err:
             raise LTIOutcomesAPIError("Malformed LTI outcome response") from err
```

## Solution

This dialog should re-use the HTML and CSS used for other dialogs elsewhere in the app, including:

- [x] It shouldn't have the **: (**
- [x] The font should be smaller
- [x] The font color should be darker
- [x] The dialog should be less wide
- [x] The dialog should be less tall

There are probably other differences too. If it can re-use the HTML and CSS that should catch them all.

### PR DESCRIPTION
**Pull request by LMS007**
### Commits

Fix incorrect fetch grade message …

The fetch grade error was incorrectly showing the wrong message

------------

- Remove ":(" from ErrorDialog's title text for submit and fetch errors
- Set font size for Dialog content
- Remove focus outline when Dialog's content pane is in focus
- Do not override font color in LMSGrader
- ~Add default font color to body ($grey-7)~
- Use standard font sizes for LMSGrader

-----------

_Updates_

**Refactored this PR to only include CSS/text issues to dialogs. Pulled out the retry feature and will include that in another PR.
** removed body color, (will fix in follow up PR)

This PR builds off the orignal here
https://github.com/hypothesis/lms/pull/2329

fixes #2320

**Before**
Screen Shot 2021-02-10 at 2 39 24 PM

**After**
Screen Shot 2021-02-10 at 2 39 59 PM

### CODE REVIEW

File: lms/static/scripts/frontend_apps/components/ErrorDialog.js [hunk 1]
```diff
@@ -1,14 +1,21 @@
 import { createElement } from 'preact';
+import { useRef } from 'preact/hooks';
 
+import Button from './Button';
 import ErrorDisplay from './ErrorDisplay';
 import Dialog from './Dialog';
 
 /**
  * @typedef ErrorDialogProps
+ * @prop {boolean} [busy] -
```
Comment (LMS007) [inline lms/static/scripts/frontend_apps/components/ErrorDialog.js:10]: This is actually not used yet, but could be if we replace BaseDialog.. I sorta brought it in with the other retry onRetry prop

File: lms/static/scripts/frontend_apps/components/SubmitGradeForm.js [hunk 2]
```diff
@@ -225,16 +226,21 @@ export default function SubmitGradeForm({ student }) {
...
+            setSubmitGradeError('');
+            onSubmitGrade(e);
+          }}
         />
       )}
       {!!fetchGradeError && (
         <ErrorDialog
           title="Fetch Grade Error"
-          error={{ message: submitGradeError }}
+          error={{ message: fetchGradeError }}
```
Comment (LMS007) [inline lms/static/scripts/frontend_apps/components/SubmitGradeForm.js:238]: This was actually a bug that I caused! It's why "Malformed LTI..." message was not reporting on fetch errors and we were not able to distinguish between any type of fetch error.

File: lms/static/styles/components/_Dialog.scss [hunk 3]
```diff
@@ -22,6 +23,8 @@
 }
 
 .Dialog__content {
+  @include mixins.font-normal;
+  @include focus.outline-on-keyboard-focus;
```
Comment (LMS007) [inline lms/static/styles/components/_Dialog.scss:27]: This prevents the Dialog box from having that big blue (or grey) outline ring.

File: lms/static/styles/frontend_apps.scss [hunk 4]
```diff
@@ -32,4 +32,5 @@ body {
   font-family: var.$sans-font-family;
   font-size: var.$normal-font-size;
   line-height: var.$normal-line-height;
+  color: var.$grey-7;
```
Comment (LMS007) [inline lms/static/styles/frontend_apps.scss:35]: There was no default color...now there is!

**Comment by LMS007** [comment]
Quick note about focus ring and the "Try again" or "Authorize" button on the dialog. It won't have focus if the last action you performed was with a mouse. e.g. If you click to change students to fetch a new grade, and there is an error, then the button won't show focus (it will indeed be focused, but visibly hidden). However if you did the same thing with the keyboard, then it will show focus. 

The one exception is when you first load up the app. and you get a launch error such "Authorize". I believe in this case it will default to showing the focus ring. e.g. keyboard focus. I think that may be different from browser to browser, but more testing needs to be done.

**Comment by robertknight** [comment]
I've just started looking at this PR and it was initially confusing because there is quite a gap in scope between the original issue in https://github.com/hypothesis/lms/issues/2320 and what is included in this PR.

Reading the PR description it looks to me like there are three orthogonal sets of changes here:

1. Regression fixes
   - Fixed a bug where the fetch grade error was incorrectly showing the wrong message
2. Styling / text updates
   - Remove ":(" from ErrorDialog's title text for submit and fetch errors
   - Set font size for Dialog content
   - Remove focus outline when Dialog's content pane is in focus
   - Do not override font color in LMSGrader
   - Add default font color to body ($grey-7)
   - Use standard font sizes for LMSGrader
3. Adding retry functionality to this dialog
   - Extend the ErrorDialog component to have the ability to render a retry button and busy override similar to LaunchErrorDialog. nb. This could eventually replace BaseDialog inside LaunchErrorDialog.
   - Give grading fetch and submit errors a retry button.
   - Change LMSGrader so it can rebuild SubmitGradeForm component on onRetry callback to refetch student grades.

It looks to me like earlier PR https://github.com/hypothesis/lms/pull/2329 tried to address (1) and (2). I'm sorry to be a pain but I would prefer to review a PR that addresses (1) and (2) before (3). I know that Sean added a bunch of feedback in https://github.com/hypothesis/lms/pull/2329 which wasn't strictly on the original issue, but I still think it makes sense to try and land the fixes for the problems that were on the original issue, plus anything very closely connected, before adding new functionality.

Regarding this comment in the PR description:

>  did not remove the click-to-close feature were dialogs close when clicking outside of the content div because that has broad changing effects to every dialog in the app and we probably need to be consistent about how that works with cancelable dialogs.

I agree. This is a legitimate concern but let's not address that here as it affects other dialogs in the app.

**Review by robertknight — CHANGES_REQUESTED** [review]
I really would prefer to review and land the fixes for the style inconsistencies and incorrect error message separately from the change to add retry functionality to the dialog. Would you mind splitting these two sets of changes into different PRs.

**Comment by LMS007** [comment]
> I really would prefer to review and land the fixes for the style inconsistencies and incorrect error message separately from the change to add retry functionality to the dialog. Would you mind splitting these two sets of changes into different PRs.

Not a prob, and I agree.

**Comment by robertknight** [comment]
On master:

fetch-grade-error-master

This branch:

fetch-grade-error

Example other error dialog:

auth-failed-error

This is obviously much better, though I notice the dialog title has a different shade. The "Fetch Grade Error" text is something that needs improving. That can be done separately.

**Review by robertknight — CHANGES_REQUESTED** [review]
I suggest to remove the `body` color change from this PR and I had a query about the `line-height` change. Otherwise the changes here look good.

File: lms/static/styles/components/_ErrorDisplay.scss [hunk 5]
```diff
@@ -12,7 +12,6 @@
 
   &__links {
     white-space: normal;
-    line-height: 1.25em;
```
[the remark this answers is not in the document]
Comment (LMS007) [reply lms/static/styles/components/_ErrorDisplay.scss:15]: It was a change done originally to make the word wrapping of the links look better because the default line-height is fixed at `px` rather than `em`, but now since the font is back to default size, things look okay when wrapped. I just decided to remove the override.

**Comment by LMS007** [comment]
Follow up PR
https://github.com/hypothesis/lms/issues/2421

**Review by robertknight — APPROVED** [review]
LGTM
